spring:
  cloud:
    consul:
      host: consul
      port: 8500
  datasource:
    url: jdbc:mysql://qacmysql.cjuukq6e630o.ap-southeast-1.rds.amazonaws.com:3306/event
    username: root
    password: L8$gHn9%VzBx4Q!
